restaurant_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('restaurant_project.accounts.urls')),
                  path('', include('restaurant_project.main.urls.main')),
                  path('waiters/', include('restaurant_project.main.urls.waiters')),
                  path('kitchen/', include('restaurant_project.main.urls.kitchen')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant_project/main/models.py
from cloudinary import models as cloudinary_models
from django.contrib.auth.models import Group
from django.core.validators import MinValueValidator
from django.db import models

from restaurant_project.accounts.models import RestaurantUser


class Tables(models.Model):
    TABLE_MAX_LENGTH = 25
    TABLE_MIN_SEAT = 2

    name = models.CharField(
        max_length=TABLE_MAX_LENGTH,
    )

    max_seats = models.IntegerField(
        default=TABLE_MIN_SEAT,
        validators=(
            MinValueValidator(TABLE_MIN_SEAT),
        )
    )

    def __str__(self):
        return f'Маса: {self.name}'


class Ingredients(models.Model):
    INGREDIENTS_NAME_MAX_LENGTH = 30
    INGREDIENTS_UNIT_MAX_LENGTH = 10

    name = models.CharField(
        max_length=INGREDIENTS_NAME_MAX_LENGTH,
        unique=True,
    )

    quantity = models.FloatField(
        default=0,
    )

    unit = models.CharField(
        max_length=INGREDIENTS_UNIT_MAX_LENGTH,
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Categories(models.Model):
    CATEGORY_MAX_LENGTH = 30

    name = models.CharField(
        max_length=CATEGORY_MAX_LENGTH,
    )

    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class FoodAndDrinks(models.Model):
    FOOD_AND_DRINKS_NAME_MAX_LENGTH = 50
    MIN_PRICE_VALUE = 0.0
    name = models.CharField(
        max_length=FOOD_AND_DRINKS_NAME_MAX_LENGTH,
    )
    description = models.TextField(
        null=True,
        blank=True,
    )
    category = models.ForeignKey(
        Categories,
        on_delete=models.CASCADE,
    )
    price = models.FloatField(
        validators=(
            MinValueValidator(MIN_PRICE_VALUE),
        )
    )

    date_added = models.DateTimeField(
        auto_now_add=True,
    )

    image = cloudinary_models.CloudinaryField('image', blank=True, null=True)

    user = models.ForeignKey(
        RestaurantUser,
        on_delete=models.DO_NOTHING,
    )

    ingredients = models.ManyToManyField(
        Ingredients,
        through='FoodAndDrinksToIngredients'
    )

    def __str__(self):
        return self.name


class FoodAndDrinksToIngredients(models.Model):
    QUANTITY_MIN_VALUE = 0.0

    ingredient = models.ForeignKey(
        Ingredients,
        on_delete=models.CASCADE,
    )
    food_and_drinks = models.ForeignKey(
        FoodAndDrinks,
        on_delete=models.CASCADE,
    )
    quantity = models.FloatField(
        default=0,
        validators=(
            MinValueValidator(QUANTITY_MIN_VALUE),
        )
    )

    def __str__(self):
        return self.food_and_drinks.name


class Orders(models.Model):
    order_start_date = models.DateTimeField(
        auto_now_add=True,
    )

    order_end_date = models.DateTimeField(
        null=True,
        blank=True,
    )

    status = models.BooleanField(
        default=False,
    )

    table = models.ForeignKey(
        Tables,
        on_delete=models.DO_NOTHING,
    )

    waiter = models.ForeignKey(
        RestaurantUser,
        on_delete=models.DO_NOTHING,
    )

    def __str__(self):
        return f'Table: {self.table.name}'

    class Meta:
        ordering = ['pk']


class OrderDetails(models.Model):
    PCS_MIN_VALUE = 0.0
    order = models.ForeignKey(
        Orders,
        on_delete=models.CASCADE,
    )
    food_and_drinks = models.ForeignKey(
        FoodAndDrinks,
        on_delete=models.DO_NOTHING,
    )

    pcs = models.FloatField(
        validators=(
            MinValueValidator(PCS_MIN_VALUE),
        )
    )

    completed = models.BooleanField(
        default=False
    )

    def total_price(self):
        return self.pcs * self.food_and_drinks.price

    def __str__(self):
        return self.food_and_drinks.name

restaurant_project/main/forms/waiters_forms.py
from django.forms import ModelForm, HiddenInput

from restaurant_project.main.models import Orders, OrderDetails


class CreateOrderForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Orders
        fields = '__all__'
        widgets = {
            'waiter': HiddenInput(),
            'order_end_date': HiddenInput(),
            'status': HiddenInput(),
            'table': HiddenInput(),

        }


class CreateOrderDetailsForm(ModelForm):
    class Meta:
        model = OrderDetails
        fields = '__all__'
        widgets = {
            'order': HiddenInput(),

        }

restaurant_project/main/views/waiters.py
from datetime import datetime

from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, CreateView

from restaurant_project.common.helpers import group_required
from restaurant_project.common.view_mixins import WaitersAccess
from restaurant_project.main.forms.waiters_forms import CreateOrderDetailsForm, CreateOrderForm
from restaurant_project.main.models import Tables, Orders, FoodAndDrinks, OrderDetails, Categories


class TablesView(WaitersAccess, ListView):
    template_name = 'waiters/tables_page.html'
    model = Tables

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        orders_data = Orders.objects.filter(status=False)
        context['tables'] = Tables.objects.all()
        context['occupied_table'] = [order.table_id for order in orders_data]

        return context


class TableDetailsView(WaitersAccess, TemplateView):
    template_name = 'waiters/table_details.html'
    model = Orders

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        order = Orders.objects.filter(table_id=kwargs['pk']).filter(status=False).prefetch_related('orderdetails_set')

        cat_id = self.request.GET.get('category')
        searched_item_string = self.request.GET.get('item')
        if searched_item_string:
            searched_items = FoodAndDrinks.objects.filter(name__icontains=searched_item_string)
            context['searched_items'] = searched_items
        # order form data
        waiter = self.request.user
        table = Tables.objects.get(id=self.kwargs['pk'])
        data = {'waiter': waiter,
                'table': table}
        order_form = CreateOrderForm(initial=data)
        context['order_form'] = order_form

        context['user'] = self.request.user
        if order:
            # order details_data data
            order_details_data = {
                'order': order[0],
            }
            order_details_form = CreateOrderDetailsForm(initial=order_details_data)
            context['order_details_form'] = order_details_form
            context['order'] = order[0]
            ordered_items = order[0].orderdetails_set.all()
            context['total_sum'] = sum([item.total_price() for item in ordered_items if item.completed == True])
            sent_items_id = OrderDetails.objects.filter(order=order[0]).filter(completed=True).values('id')
            context['sent_items'] = [item['id'] for item in sent_items_id]

        context['categories'] = Categories.objects.all()
        context['items'] = FoodAndDrinks.objects.filter(category_id=cat_id)
        return context

    def get_success_url(self):
        return reverse_lazy('table details', kwargs={'pk': self.object.id})


class StartOrder(WaitersAccess, CreateView):
    template_name = 'waiters/remove_item.html'
    model = Orders
    form_class = CreateOrderForm

    def get_success_url(self):
        return reverse_lazy('table details', kwargs={'pk': self.object.table.id})


class AddItemInTheOrder(WaitersAccess, CreateView):
    template_name = 'waiters/add_item.html'
    model = OrderDetails
    form_class = CreateOrderDetailsForm

    def get_success_url(self):
        return reverse_lazy('table details', kwargs={'pk': self.object.order.table.id})


@group_required(allowed_roles=['Waiters'])
def remove_item(request, pk, *args, **kwargs):
    item = OrderDetails.objects.get(pk=kwargs.get('item_id'))
    item.delete()
    return redirect('table details', pk)


# @permission_required('Waiters')
@group_required(allowed_roles=['Waiters'])
def complete_order(request, pk):
    item = Orders.objects.get(pk=pk)
    item.status = True
    item.order_end_date = datetime.now()
    item.save()
    return redirect('tables list')

templates/waiters/add_item.html
{% extends 'base.html' %}
{% load static %}

{% block page_content %}
    <h1 class='text-center'>
        Tables
    </h1>

    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" class="container mb-5" action="{% url 'order add item' pk %}">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-primary mt-2" type="submit">Start order</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{#        <div class=" row d-flex justify-content-center align-content-center">#}
{#            <a href="{% url 'create pet photo' %}" class="btn btn-lg btn-secondary row align-self-baseline">Add#}
{#                Photo</a>#}
{#        </div>#}

{% endblock %}

templates/waiters/category_details.html
{% extends 'base.html' %}
{% load static %}

{% block page_content %}
    <h1 class='text-center'>
        recipes.category.name {{ pk }}
    </h1>

    <div class="container mb-5">
        <div class="row mb-5">
        {% for r in recipes %}
            <div class="card ml-3 mb-3" style="width: 18rem;">
                <img src="{{ r.image.url }}"
                     class="card-img-top" alt="Photo description">
                <div class="card-body">

                    <h5 class="card-title">{{ r.name }}</h5>
                    <!-- Button to the Photo Details Page -->
                    <a href="#" class="btn btn-primary">Add</a>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>

{% endblock %}

templates/waiters/new_order.html
{% extends 'base.html' %}
{% load static %}

{% block page_content %}
    <h1 class='text-center'>
        Tables
    </h1>

    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" class="container mb-5" action="{% url 'order start' pk %}">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-primary mt-2" type="submit">Start order</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{#        <div class=" row d-flex justify-content-center align-content-center">#}
{#            <a href="{% url 'create pet photo' %}" class="btn btn-lg btn-secondary row align-self-baseline">Add#}
{#                Photo</a>#}
{#        </div>#}

{% endblock %}

templates/waiters/remove_item.html
{% extends 'base.html' %}
{% load static %}

{% block page_content %}
    <h1 class='text-center'>
        Tables
    </h1>

    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" class="container mb-5" action="{% url 'order start' pk %}">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-primary mt-2" type="submit">Start order</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{#        <div class=" row d-flex justify-content-center align-content-center">#}
{#            <a href="{% url 'create pet photo' %}" class="btn btn-lg btn-secondary row align-self-baseline">Add#}
{#                Photo</a>#}
{#        </div>#}

{% endblock %}

templates/waiters/table_details.html
{% extends 'base.html' %}
{% load static %}

{% block page_content %}
    <h1 class='text-center'>
        Маса {{ pk }}
    </h1>
    {% if not order %}
        <div class="row d-flex justify-content-center align-content-center">
            <div class="text-center">
                <form method="post" class="container mb-5" action="{% url 'order start' pk %}">
                    {% csrf_token %}
                    {{ order_form }}
                    <button class="btn btn-primary mt-2" type="submit">Започни поръчка</button>
                </form>
            </div>
        </div>
    {% else %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    {% for cat in categories %}
                        <li class="nav-item active">
                            <a href="{% url 'table details' pk %}?category={{ cat.id }}"
                               class="btn navbar-brand">{{ cat.name }}</a>
                        </li>
                    {% endfor %}

                </ul>
                <form role="form" method="GET" class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" name="item" placeholder="Търси" aria-label="Search">
                    <button class="btn btn-primary my-2 my-sm-0" type="submit">Търси</button>
                </form>
            </div>
        </nav>
        <div class="container mb-5">
            <div class="row">
                <div class="col-lg-6 mx-auto">
                    <div class="card ">
                        <div class="card-header">
                            {% for item in searched_items %}
                                <div class="d-flex justify-content-between">
                                    <form method="post" action="{% url 'order add item' pk %}">
                                        {% csrf_token %}
                                        {{ order_details_form.order }}
                                        <input type="text" value="{{ item.name }}" disabled readonly>
                                        <input type="hidden" name="food_and_drinks" id="id_food_and_drinks"
                                               value="{{ item.id }}" required>
                                        {{ order_details_form.pcs }}
                                        <button>Добави</button>
                                    </form>
                                </div>
                            {% endfor %}
                            {% for item in items %}
                                <div class="d-flex justify-content-between">
                                    <form method="post" action="{% url 'order add item' pk %}">
                                        {% csrf_token %}
                                        {{ order_details_form.order }}
                                        <input type="text" value="{{ item.name }}" disabled readonly>
                                        <input type="hidden" name="food_and_drinks" id="id_food_and_drinks"
                                               value="{{ item.id }}" required>
                                        {{ order_details_form.pcs }}
                                        <button type="submit">Добави</button>
                                    </form>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% endif %}

    {% if order %}
    <div class="event-schedule-area-two bg-color pad100">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title text-center">
                        <div class="title-text">
                            <h2>Поръчка</h2>
                        </div>
                    </div>
                </div>
                <!-- /.col end-->
            </div>
            <!-- row end-->
            <div class="row">
                <div class="col-lg-12">
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade active show" id="home" role="tabpanel">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th class="text-center" scope="col">#</th>
                                        <th scope="col">Ястие/напитка</th>
                                        <th scope="col">Наименование</th>
                                        <th scope="col">Брой</th>
                                        <th scope="col">Ед. Цена</th>
                                        <th scope="col">Цена</th>
                                        <th class="text-center" scope="col">Статус</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for item in order.orderdetails_set.all %}
                                        <tr class="inner-box">
                                            <th scope="row">
                                                <div class="r-no">
                                                    <span>{{ forloop.counter }}</span>
                                                </div>
                                            </th>
                                            <td>
                                                <div class="event-img">
                                                    <img style="width: auto; height: 50px;" class="rounded float-right"
                                                         src="{{ item.food_and_drinks.image.url }}"
                                                         alt="{{ item.food_and_drinks }}"/>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="r-no">
                                                    <span>{{ item.food_and_drinks }}</span>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="r-no">
                                                    <span>{{ item.pcs|floatformat:0 }}</span>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="r-no">
                                                    <span>{{ item.food_and_drinks.price|floatformat:2 }} лева</span>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="r-no">
                                                    <span>{{ item.total_price|floatformat:2 }} лева</span>
                                                </div>
                                            </td>
                                            <td>
                                                {% if item.id not in sent_items %}
                                                    <div class="primary-btn">
                                                        <a href="{% url 'remove item' pk item.id %}"
                                                           class="btn btn-warning">Откажи</a>
                                                    </div>

                                                {% else %}
                                                    <div class="r-no">
                                                        <span>Готово</span>
                                                    </div>

                                                {% endif %}
                                            </td>
                                        </tr>

                                    {% endfor %}
                                    <tr>
                                        <th class="text-center" scope="col"></th>
                                        <th scope="col"></th>
                                        <th scope="col"></th>
                                        <th scope="col"></th>
                                        <th scope="col">Сума за плащане:</th>
                                        <th class="text-center" scope="col">{{ total_sum|floatformat:2 }} лева</th>
                                        <th class="text-center" scope="col"></th>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

        <div>
            <a href="{% url 'complete order' order.id %}" class="btn btn-success">Завърши поръчка</a>
        </div>
    {% endif %}
{% endblock %}

{% block bottom_scripts %}
    <script>
        setTimeout(function(){
           window.location.reload(1);
        }, 60000);
    </script>
{% endblock %}

templates/waiters/tables_page.html
{% extends 'base.html' %}
{% load static %}

{% block page_content %}
    <h1 class='text-center'>
        Tables
    </h1>


    <div class="container mb-5">
        <div class="row mb-5">
            {% for table in tables %}
                <div class="card ml-3 mb-3" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Маса: {{ table.name }}</h5>
                        <p class="card-text">До: {{ table.max_seats }} места.</p>

                        <a href="{% url 'table details' table.id %}" class="btn btn-default">
                        {% if table.id not in occupied_table %}
                        <img src="{% static 'images/free_table.jpg' %}"
                             class="card-img-top" alt="Photo description">
                        {% else %}
                        <img src="{% static 'images/occupied_table.jpg' %}"
                             class="card-img-top" alt="Photo description">
                        {% endif %}

                    </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{#        <div class=" row d-flex justify-content-center align-content-center">#}
{#            <a href="{% url 'create pet photo' %}" class="btn btn-lg btn-secondary row align-self-baseline">Add#}
{#                Photo</a>#}
{#        </div>#}

{% endblock %}